# Generated by Django 4.2.16 on 2024-11-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=50)),
                ('ttb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_bas_r', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bkpr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_fetched', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
